//! Build script: generates the parity test file (one `#[test]` per fixture)
//! from `core/tests/fixtures/*.json`. Regenerates whenever a fixture is
//! added or changed, so the harness and the fixture set can never drift.

#[allow(clippy::panic)] // build scripts report configuration errors by panicking
fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap_or_default();
    if manifest.is_empty() {
        panic!("CARGO_MANIFEST_DIR is not set");
    }
    let out_dir = std::env::var("OUT_DIR").unwrap_or_else(|_| panic!("OUT_DIR is not set"));

    let fixtures_dir = std::path::Path::new(&manifest)
        .join("..")
        .join("tests")
        .join("fixtures");
    let entries = std::fs::read_dir(&fixtures_dir)
        .unwrap_or_else(|e| panic!("cannot read fixtures dir {}: {e}", fixtures_dir.display()));

    let mut names: Vec<String> = Vec::new();
    for entry in entries {
        let Ok(entry) = entry else { continue };
        let path = entry.path();
        if path.extension().is_some_and(|x| x == "json") {
            if let Some(file_name) = path.file_name() {
                names.push(file_name.to_string_lossy().into_owned());
            }
        }
    }
    names.sort();
    if names.is_empty() {
        panic!("no parity fixtures found in {}", fixtures_dir.display());
    }

    let mut out = String::from("// @generated by pw-engine/build.rs — do not edit.\n");
    for name in &names {
        out.push_str(&format!(
            "#[test]\nfn {}() {{ check_fixture(\"{name}\"); }}\n",
            sanitize_ident(name)
        ));
    }

    let generated = std::path::Path::new(&out_dir).join("parity_tests.rs");
    std::fs::write(&generated, out)
        .unwrap_or_else(|e| panic!("cannot write {}: {e}", generated.display()));

    println!("cargo:rerun-if-changed=../tests/fixtures");
}

/// Turn a fixture file stem into a valid Rust test function identifier.
#[allow(clippy::panic)]
fn sanitize_ident(file_name: &str) -> String {
    let stem = file_name.strip_suffix(".json").unwrap_or(file_name);
    let mut ident: String = stem
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect();
    ident = ident.to_ascii_lowercase();
    if ident.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        ident.insert(0, 'f');
    }
    if ident.is_empty() {
        panic!("fixture name collapses to empty identifier: {file_name}");
    }
    ident
}
